### ISSUE TITLE
Fatal error: exception Spoc.Kernel.No_source_for_device(_)

### ISSUE THREAD

**Issue by UnixJunkie** [mathiasbourgoin/SPOC#42]
While trying to run one of the tests:

    # ./build/Bytecode/Game.byte 
    Will use device : Quadro M4000
    Fatal error: exception Spoc.Kernel.No_source_for_device(_)

What should I do to fix that?

**Comment by mathiasbourgoin** [comment]
This is probably because your Cuda version is not compatible with your GCC version.
Here are the system requirements for linux with Cuda 8.0 http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

By default, the SPOC makefile does not compile Cuda kernels if the default GCC on th system is incompatible wit Cuda.

This is an old CUDA problem.
The common solution is to have multiple GCC versions installed.

I changed the SPOC makefile 880368c9c592767c4b849fcb2b3cbc207e2258b2 to give more feedback to the user when this problem arise.
